apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port: 3306
      targetPort: vprodb-port
      protocol: TCP
  selector:
    app: vprodb #same name as label in vpro-db-deploy