apiVersion: v1
kind: Service
metadata:
  name: vprocache01 #we got this name from application.properties file
spec:
  ports:
    - port: 11211
      targetPort: vpromc-port
      protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP