apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - name: vprodb-port
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret #iz app-secret
                  key: db-pass
          resources:
            limits:
              memory: 512Mi
              cpu: "250m"
            requests:
              memory: 256Mi
              cpu: "80m"

      volumes:
        - name: mysql-volume
          # directory location on hoast
          hostPath:
            path: /vproapp-db-data
            type: DirectoryOrCreate
